//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkTree.Examples.Web.EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeData
    {
        public int ID { get; set; }
        public string Term { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
